Ability to display either all violations, or only those blocking
friendsoftwig/twigcs pull request #125
Opened 2020-02-10 20:04 UTC by bensquire

This PR address #104  the ability to filter the output of the LintCommand. The new option `display` has 2 valid values:

`blocking` - Is all violations causing a non-zero exit code

`all` - Is all violations, regardless of whether they caused a non-zero exit code or not

So for example:

```
php bin/twigcs ./tests/data/exclusion/bad/mixed.html.twig --severity=error --display=blocking
```
Would output only ERRORs

```
php bin/twigcs ./tests/data/exclusion/bad/mixed.html.twig --severity=error --display=all
```
Would output ERRORs and WARNINGs

2020-02-10 20:16 UTC, Ciloe requested changes

2020-02-10 20:16 UTC, Ciloe commented on README.md
> +twigcs /path/to/views --severity error --display blocking
Can you add the `all` option in documentation to present all possibilities at this option ?

2020-02-10 20:16 UTC, Ciloe commented on src/Console/LintCommand.php
> +        $filteredViolations = [];
This lines to the return can be replaced by an `array_filter` function

2020-02-10 20:16 UTC, Ciloe commented on src/Validator/Violation.php
> +     * Violation constructor.
This line can be removed

2020-02-10 21:00 UTC, bensquire commented
@Ciloe Should be updated as requested.

2020-02-10 21:51 UTC, Ciloe approved these changes

2020-02-11 08:40 UTC, OwlyCode commented
Thank you @bensquire!

2020-02-11 08:40 UTC, merged