Issue #162 : Add tests for equals comparision in function as attribute
friendsoftwig/twigcs pull request #164
Opened 2020-12-15 14:49 UTC by Ciloe

Signed-off-by: Jimmy ESCRICH <jescrich@ruedesvignerons.com>

2021-01-04 14:14 UTC, stof requested changes

2021-01-04 14:14 UTC, stof commented on tests/Twig3FunctionalTest.php
> +            die;
this should be removed

2021-01-05 16:52 UTC, Ciloe commented on tests/Twig3FunctionalTest.php
> +        }
```suggestion
```

2021-01-15 15:03 UTC, stof commented
@Ciloe anything missing to finish that bugfix ?

2021-01-25 14:54 UTC, stof commented
Hello @Ciloe. any chance to get this merged (and released) ?

2021-01-26 10:27 UTC, Ciloe commented
Seen with @OwlyCode, we will merge soon

2021-02-04 12:40 UTC, OwlyCode approved these changes

2021-02-04 12:40 UTC, merged